# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# yamlのformatterによってはズレるので注意
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: end-of-file-fixer
        types: [python]
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        language_version: python3
        types: [python]
