version: "3"

services:
  server:
    build:
      context: ./server
      dockerfile: Dev_Dockerfile
    container_name: server
    restart: always
    env_file:
      - server.env
    volumes:
      - ./server/:/server/
    ports:
      - 8080:8080
    command: uvicorn setup:app --reload --host 0.0.0.0 --port 8080
  db:
    image: postgres:latest
    container_name: db
    restart: always
    env_file:
      - db.env
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
  front:
    build:
      context: ./front
      dockerfile: Dev_Dockerfile
    container_name: front
    env_file:
      - client.env
      - client_secret.env
    volumes:
      - ./front/app/:/usr/src/app
    ports:
      - 3000:3000
    command: /bin/sh -c 'npm install && npm run dev'
