FROM node:16.13.1

WORKDIR /usr/src/app

ENV NEXT_PUBLIC_SERVER_PATH https://api.heroku.com/apps/hikkoshiori-stg
ENV NEXTAUTH_URL https://api.heroku.com/apps/hikkoshiori-stg-front
ENV SECRET 1on/Cd0hTvnNLSWN2M5uMZU/4xPjNTid5OzsWlHapE0=
ENV GOOGLE_CLIENT_ID 178808764788-qoqhec9ln3967or7r1qfekvvtkjot5nf.apps.googleusercontent.com
ENV GOOGLE_CLIENT_SECRET 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

EXPOSE $PORT
